name: EAS Build and Deploy

on:
  push:
    branches:
      - main
    paths:
      - "advancedmlappreactnative/**"
  workflow_dispatch:

jobs:
  build:
    name: EAS Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: npm
          cache-dependency-path: advancedmlappreactnative/package-lock.json

      - name: Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Install dependencies
        working-directory: advancedmlappreactnative
        run: npm ci

      - name: Copy keystore
        working-directory: advancedmlappreactnative
        env:
          KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}
        run: |
          mkdir -p android/app
          echo "$KEYSTORE_BASE64" | base64 --decode > android/app/release.keystore

      - name: Build and deploy to Firebase
        working-directory: advancedmlappreactnative
        env:
          FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
          FIREBASE_CLI_TOKEN: ${{ secrets.FIREBASE_CLI_TOKEN }}
          FIREBASE_GROUPS: ${{ secrets.FIREBASE_GROUPS }}
        run: |
          # Install Firebase CLI
          npm install -g firebase-tools

          # Build with EAS
          eas build --platform android --profile firebase --non-interactive --no-wait

          # Get the latest build URL
          BUILD_URL=$(eas build:list --platform android --status finished --non-interactive --json | jq -r '.[0].artifacts.buildUrl')

          # Download the APK
          curl -o app-release.apk "$BUILD_URL"

          # Deploy to Firebase
          firebase appdistribution:distribute app-release.apk \
            --app "$FIREBASE_APP_ID" \
            --token "$FIREBASE_CLI_TOKEN" \
            --groups "$FIREBASE_GROUPS" \
            --release-notes "Built with EAS via GitHub Actions"
