name: Deploy to Firebase App Distribution

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to Firebase
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: "17"

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.3"
          bundler-cache: true

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        run: |
          npm ci
          cd android
          bundle install

      - name: Install Fastlane plugins
        run: |
          cd android
          bundle exec fastlane add_plugin firebase_app_distribution

      - name: Base64 to file
  # You may pin to the exact commit or the version.
  # uses: davidSchuppa/base64Secret-toFile-action@199e78f212c854d2284fada7f3cd3aba3e37d208
        uses: davidSchuppa/base64Secret-toFile-action@v3
        with:
    # The name of the github secret
          secret: ${{ secrets.KEYSTORE_BASE64 }}  # default is 
    # The name of the output file
          filename: release.keystore # default is 
    # The destination path of the output file
          destination-path: android/app # default is 
          
      - name: Create .env file
        env:
          FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
          FIREBASE_CLI_TOKEN: ${{ secrets.FIREBASE_CLI_TOKEN }}
          FIREBASE_GROUPS: ${{ secrets.FIREBASE_GROUPS }}
        run: |
          echo "FIREBASE_APP_ID=\"$FIREBASE_APP_ID\"" > android/.env
          echo "FIREBASE_CLI_TOKEN=\"$FIREBASE_CLI_TOKEN\"" >> android/.env
          echo "FIREBASE_GROUPS=\"$FIREBASE_GROUPS\"" >> android/.env
          echo "PROJECT_ROOT=\"$GITHUB_WORKSPACE\"" >> android/.env
          echo "APK_PATH=\"\"" >> android/.env

          # Also create the same file in fastlane directory
          mkdir -p android/fastlane
          cp android/.env android/fastlane/.env

      - name: Deploy to Firebase App Distribution
        run: |
          cd android
          bundle exec fastlane android deploy_to_firebase

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: apk
          path: android/app/build/outputs/apk/release/*.apk
          retention-days: 7
